HOME_TOGGLE_LOCATOR = "//button[@title='Toggle']"
DOWNLOAD_TOGGLE_LOCATOR = "//ol[1]/li[3]/span/button[@aria-label='Toggle']"
ELEMENTS_MENU_LOCATOR = "//div[@class='category-cards']/div[1]"
DOUBLE_CLICK_BUTTON_LOCATOR = "//button[@id='doubleClickBtn']"
CHECKBOX_WORD_FILE = "//label[@for='tree-node-wordFile']/span[1]"
CHECK_TEXT_SUCCESS = "//span[@class='text-success']"
BUTTONS_CLICK_ID = "item-4"
CHECKBOX_CLICK_ID = "item-1"
RIGHT_CLICK_BUTTON_LOCATOR = "//button[@id='rightClickBtn']"
CLICK_ME_BUTTON_LOCATOR = "//button[text()='Click Me']"